name: Java CI with Maven & Checkstyle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Compile project
        run: mvn clean test-compile

      - name: Run Task 1 tests
        run: mvn -Dtest=Task1Test test || true

      - name: Run Task 2 tests
        run: mvn -Dtest=Task2Test test || true

      - name: Run Task 3 tests
        run: mvn -Dtest=Task3Test test || true

      - name: Run Task 4 tests
        run: mvn -Dtest=Task4Test test || true

      - name: Run Task 5 tests
        run: mvn -Dtest=Task5Test test || true

      - name: Run Checkstyle
        run: mvn checkstyle:check || true