name: Autograding Tests

on:
  push:
  workflow_dispatch:
  repository_dispatch:

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      - name: Compile
        run: mvn clean compile

      - name: Run Task 1 Tests
        uses: education/autograding-command-grader@v1
        with:
          test-name: Task 1
          setup-command: mvn clean test-compile
          command: mvn -Dtest=Task1Test test
          timeout: 10
          max-score: 1

      - name: Run Task 2 Tests
        uses: education/autograding-command-grader@v1
        with:
          test-name: Task 2
          setup-command: mvn clean test-compile
          command: mvn -Dtest=Task2Test test
          timeout: 10
          max-score: 1

      - name: Run Task 3 Tests
        uses: education/autograding-command-grader@v1
        with:
          test-name: Task 3
          setup-command: mvn clean test-compile
          command: mvn -Dtest=Task3Test test
          timeout: 10
          max-score: 2

      - name: Run Task 4 Tests
        uses: education/autograding-command-grader@v1
        with:
          test-name: Task 4
          setup-command: mvn clean test-compile
          command: mvn -Dtest=Task4Test test
          timeout: 10
          max-score: 2

      - name: Run Task 5 Tests
        uses: education/autograding-command-grader@v1
        with:
          test-name: Task 5
          setup-command: mvn clean test-compile
          command: mvn -Dtest=Task5Test test
          timeout: 10
          max-score: 3